filepath: ""
helmfiles:
- path: helmfiles/jx/helmfile.yaml
- path: helmfiles/kuberhealthy/helmfile.yaml
- path: helmfiles/nginx/helmfile.yaml
- path: helmfiles/jx-jx-demo-gke2-prod/helmfile.yaml
templates: {}
renderedvalues: {}
