apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: jenkins-x-labs-bdd1
    provider: kubernetes
    registry: ghcr.io
    zone: us-central1-a
  ingress:
    domain: 35.192.119.220.nip.io
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kuberhealthy: true
  pipelineUser:
    username: jstrachan
  repository: bucketrepo
  secretStorage: local
  storage:
  - name: logs
    url: gs://logs-jstrachan-tekton-prod-0b0e121c60fc
  - name: reports
    url: gs://reports-jstrachan-tekton-prod-0b0e121c60fc
  - name: repository
    url: gs://repository-jstrachan-tekton-prod-0b0e121c60fc
  vault: {}
  webhook: lighthouse
