filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: myapps
repositories:
- name: dev
  url: http://chartmuseum-jx.34.89.8.12.nip.io
- name: dev2
  url: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
releases:
- chart: dev2/nodey560
  version: 0.0.12
  name: nodey560
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
