# Source: nodey560/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-03-26T17:35:42Z"
  deletionTimestamp: null
  name: 'nodey560-0.0.13'
  namespace: myapps
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 0.0.13
      sha: 3c79680e670d569e66dd109dded609320aa808f1
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: dda11a5d70ca6d6be0be5d2501ebc390c7d362d0
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: noreply@github.com
        name: GitHub
      message: Update index.html
      sha: e89041668d588ef604530e50f065cf9896dcdf20
  gitHttpUrl: https://github.com/jstrachan/nodey560
  gitOwner: jstrachan
  gitRepository: nodey560
  name: 'nodey560'
  releaseNotesURL: https://github.com/jstrachan/nodey560/releases/tag/v0.0.13
  version: v0.0.13
status: {}
