filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx
repositories:
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
releases:
- chart: jx3/jxboot-helmfile-resources
  version: 1.0.37
  name: jxboot-helmfile-resources
  values:
  - ../../versionStream/charts/jx3/jxboot-helmfile-resources/values.yaml.gotmpl
  - jx-values.yaml
  - basicAuthSecrets:
      enabled: false
- chart: jx3/jenkins-x-crds
  version: 3.0.5
  name: jenkins-x-crds
  values:
  - ../../versionStream/charts/jx3/jenkins-x-crds/values.yaml.gotmpl
  - jx-values.yaml
- chart: jx3/local-external-secrets
  version: 0.0.6
  name: local-external-secrets
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
