filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx
repositories:
- name: jenkins-x
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
releases:
- chart: /Users/jstrachan/workspace/workspace/java/jxboot-helmfile-resources/jxboot-helmfile-resources
  name: jxboot-helmfile-resources
  values:
  - ../../versionStream/charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
  - jx-values.yaml
  - basicAuthSecrets:
      enabled: false
- chart: jx3/jenkins-x-crds
  version: 3.0.5
  name: jenkins-x-crds
  values:
  - ../../versionStream/charts/jx3/jenkins-x-crds/values.yaml.gotmpl
  - jx-values.yaml
- chart: jx3/local-external-secrets
  version: 0.0.6
  name: local-external-secrets
  values:
  - jx-values.yaml
- chart: jx3/jx-kh-check
  version: 0.0.56
  name: health-checks-jx
  values:
  - ../../versionStream/charts/jx3/health-checks-jx/values.yaml.gotmpl
  - jx-values.yaml
templates: {}
renderedvalues: {}
