filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: kuberhealthy
repositories:
- name: kuberhealthy
  url: https://comcast.github.io/kuberhealthy/helm-repos
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
releases:
- chart: kuberhealthy/kuberhealthy
  version: 2.2.0
  name: kuberhealthy
  values:
  - ../../versionStream/charts/kuberhealthy/kuberhealthy/values.yaml.gotmpl
  - jx-values.yaml
- chart: jx3/jx-kh-check
  version: 0.0.56
  name: jx-kh-check
  values:
  - ../../versionStream/charts/jx3/jx-kh-check/values.yaml.gotmpl
  - jx-values.yaml
- chart: jx3/jenkins-x-crds
  version: 3.0.5
  name: jenkins-x-crds
  values:
  - ../../versionStream/charts/jx3/jenkins-x-crds/values.yaml.gotmpl
  - jx-values.yaml
- templates: {}
renderedvalues: {}
